name 'consul_kv'
maintainer 'David Petzel'
maintainer_email 'davidpetzel@gmail.com'
license 'apache2'
description 'LWRP for interacting with Consul Key/Value store'
long_description 'Installs/Configures consul_kv'
version '1.1.0'
